name: publish

on: workflow_dispatch

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: |
        dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore -c Release
    - name: Test
      run: |
        dotnet test --no-build
    - name: Pack
      run: |
        dotnet pack --no-restore --version-suffix $(date "+%Y.%m%d") -c Release -o out DH.Swagger/DH.Swagger.csproj
    - name: Publish
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.chuangchu.net/v3/index.json --api-key ${{ secrets.mynugetKey }}